const ActionTypes = {
    SAVE_RECIPE: 'SAVE_RECIPE',
    GET_RECIPE: 'GET_RECIPE',
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    UPDATE_VALUE: 'UPDATE_VALUE'
}

export default ActionTypes;