const ActionTypes = {
    SAVE_RECIPE: 'SAVE_RECIPE',
    GET_RECIPE: 'GET_RECIPE',
    NEW_RECIPE: 'NEW_RECIPE',
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    ADD_STEP: 'ADD_STEP',
    UPDATE_VALUE: 'UPDATE_VALUE',
    SERVER_REQUEST: "SERVER_REQUEST",
    OPEN_CONTENT: "OPEN_CONTENT"
}

export default ActionTypes;