const ActionTypes = {
    SAVE_RECIPE: 'SAVE_RECIPE',
    GET_RECIPE: 'GET_RECIPE',
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    ADD_STEP: 'ADD_STEP',
    DELETE_STEP: 'DELETE_STEP',
    DELETE_INGREDIENT: 'DELETE_INGREDIENT',
    UPDATE_VALUE: 'UPDATE_VALUE'
}

export default ActionTypes;