INSERT INTO `ingredients` (`ingredientId`, `ingredientName`, `defaultUnit`) VALUES
(1, 'Applesauce', 'cup'),
(2, 'Balsamic vinegar', 'Tbsp'),
(3, 'Baking soda', 'Tbsp'),
(4, 'Baking powder', 'Tbsp'),
(5, 'Barbecue sauce', 'Tbsp'),
(6, 'Bay leaves', 'item'),
(7, 'Beef bouillon', 'item'),
(8, 'Chicken bouillon', 'item'),
(9, 'Vegetable bouillon', 'item'),
(10, 'Breadcrumbs', 'cup'),
(11, 'Brown rice', 'cup'),
(12, 'Brown sugar', 'tsp'),
(13, 'Canned tomatoes', 'oz'),
(14, 'Canned tuna fish', 'oz'),
(15, 'Carrots', 'item'),
(16, 'Cocoa powder', 'Tbsp'),
(17, 'Cooking spray', 'tsp'),
(18, 'Cornmeal', 'Tbsp'),
(19, 'Cornstarch', 'tsp'),
(20, 'Basil', 'tsp'),
(21, 'Oregano', 'tsp'),
(22, 'Thyme', 'tsp'),
(23, 'Rosemary', 'tsp'),
(24, 'Dill', 'tsp'),
(25, 'Cilantro', 'tsp'),
(26, 'Tarragon', 'tsp'),
(27, 'Chives', 'tsp'),
(28, 'Cinnamon', 'tsp'),
(29, 'Nutmeg', 'tsp'),
(30, 'Cumin', 'tsp'),
(31, 'Paprika', 'tsp'),
(32, 'Mustard', 'tsp'),
(33, 'Ginger', 'tsp'),
(34, 'Allspice', 'tsp'),
(35, 'Cayenne pepper', 'tsp'),
(36, 'Garlic', 'tsp'),
(37, 'Ginger', 'tsp'),
(38, 'Honey', 'tsp'),
(39, 'Hot sauce', 'tsp'),
(40, 'Jam', 'tsp'),
(41, 'Kosher salt', 'tsp'),
(42, 'Lemons', 'item'),
(43, 'limes', 'item'),
(44, 'Lentils', 'cup'),
(45, 'Maple syrup', 'Tbsp'),
(46, 'Mayonnaise', 'Tbsp'),
(47, 'Oatmeal', 'tsp'),
(48, 'Olive oil', 'Tbsp'),
(49, 'Onions', 'item'),
(50, 'Pasta', 'cup'),
(51, 'Peanut butter', 'Tbsp'),
(52, 'Peppercorns', 'tsp'),
(53, 'Powdered sugar', 'cup'),
(54, 'Prepared mustard', 'tsp'),
(55, 'Potatoes, russet', 'item'),
(56, 'Potatoes, small red', 'item'),
(57, 'Red wine vinegar', 'Tbsp'),
(58, 'Semisweet chocolate chips', 'cup'),
(59, 'Solid shortening', 'Tbsp'),
(60, 'Soy sauce', 'Tbsp'),
(61, 'Tomato paste', 'oz'),
(62, 'Unbleached white flour', 'cup'),
(63, 'Unsweetened chocolate', 'cup'),
(64, 'Vanilla', 'tsp'),
(65, 'Vegetable oil', 'Tbsp'),
(66, 'White sugar', 'Tbsp'),
(67, 'White wine vinegar', 'Tbsp'),
(68, 'Worcestershire sauce', 'Tbsp'),
(69, 'Yeast', 'Tbsp'),
(81, 'Apple(s)', 'Bag(s)'),
(84, 'Corn bread stuffing', 'Bag(s)'),
(85, 'Chicken broth', 'tsp'),
(86, 'Onion', 'item'),
(87, 'Celery', 'item'),
(88, 'Egg(s)', 'item'),
(89, 'Water', 'tsp');

INSERT INTO `person` (`personId`, `firstName`, `lastName`, `email`) VALUES
(0, 'Max', 'DeAngelis', 'Maxwell.DeAngelis@gmail.com');

INSERT INTO `users` (`userId`, `userName`, `password`, `status`, `roleType`) VALUES
(0, 'deanm', 'ff4c88d7450f4e074932ccd1b8c0d188', 'current', 'admin');
